version: 2
project_name: backmeup

before:
  hooks:
  - go mod download

builds:
  - main: ./cmd/backmeup
    ldflags: -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: '{{ .ProjectName }}-{{.Version}}_checksums.txt'
changelog:
  disable: true

archives:
  - format: binary
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version}}_
      {{- if eq .Os "darwin" }}macOS{{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}
