project_name: backmeup

before:
  hooks:
  - go mod download

builds:
  - main: ./cmd/main.go
    ldflags: -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: '{{ .ProjectName }}-{{.Version}}_checksums.txt'
changelog:
  skip: true

archives:
  - format: binary
    replacements:
      386: i386
      darwin: macOS
    name_template:
