name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Release build
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
