name: Build and test pushes and PRs
on: [push, pull_request]

jobs:
  build:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build application
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Run tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v .